name: Workflow Directory Check

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  workflow_directory_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Fetch Latest Default Branch
        run: git fetch origin ${{ github.event.default_branch }}:${{ github.event.default_branch }}

      - name: Get Latest Default Branch Commit
        id: default_commit
        run: echo "DEFAULT_COMMIT_SHA=$(git rev-parse origin/${{ github.event.default_branch }})" >> $GITHUB_ENV

      - name: Check Workflow Directory Changes
        id: diff
        run: |
          WORKFLOW_DIFF=$(git diff --name-only $DEFAULT_COMMIT_SHA...${{ github.sha }} .github/workflows)
          echo "WORKFLOW_DIFF=$WORKFLOW_DIFF" >> $GITHUB_ENV

      - name: Display Diff
        run: echo "Workflow Diff: $WORKFLOW_DIFF"

      - name: Update Status Check
        if: env.WORKFLOW_DIFF != ''
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "failure",
              "context": "workflow-directory-check",
              "description": "Workflow directories have changes",
              "target_url": "https://example.com/workflow-check-results"
            }'
