name: Dispatch Event Listener

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered Action
        run: echo "Triggered action ran"
