name: Trigger Workflow

on:
  push:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Initiate the Workflow on Main
        run: |
          echo "This triggers the workflow on main."
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"





